const ONE_MINUTE_MILLISECONDS = 60 * 1000;
const ONE_HOUR_MILLISECONDS = 60 * ONE_MINUTE_MILLISECONDS;
const ONE_DAY_MILLISECONDS = 24 * ONE_HOUR_MILLISECONDS;

export { ONE_MINUTE_MILLISECONDS, ONE_HOUR_MILLISECONDS, ONE_DAY_MILLISECONDS };
